/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.yappy;

import java.io.IOException;

import javassist.ByteArrayClassPath;
import javassist.ClassPool;
import javassist.CtClass;
import javassist.NotFoundException;

public class MccMod {

    private static CtClass loadClass(String name) throws IOException, NotFoundException {
        byte[] b = MccMod.class.getClassLoader().getResourceAsStream(name + ".class").readAllBytes();
        var cp = ClassPool.getDefault();
        cp.insertClassPath(new ByteArrayClassPath(name, b));

        return cp.get(name);
    }

    public static void init() {
        try {
            CtClass clsMc = loadClass("MasaoConstruction");
            Class<?> cls = clsMc.toClass();
            System.out.println(cls);
            var con = cls.getDeclaredConstructor();
            System.out.println(con);
            var obj = con.newInstance();
            System.out.println(obj);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
