/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.yappy.mccport;

public class AppletMod {

    public AppletMod() {
        System.out.println("AppletMod constructor");
    }

    public String getParameter(String name) {
        System.out.println("getParameter: " + name);
        return null;
    }

}
