/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.yappy.mccport;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Panel;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;

import javax.imageio.ImageIO;

public abstract class AppletMod extends Panel implements Runnable {

    // must access with synchronized(this)
    private class SharedState {
        boolean isStarted = false;
        Thread mcThread = null;
        boolean isExiting = false;
    }
    private SharedState sharedState = new SharedState();
    private Map<String, String> parameters = new HashMap<>();

    public AppletMod() {
        super();
        System.out.println("AppletMod constructor");
        setSize(MccMod.MC_APPLET_W, MccMod.MC_APPLET_H);
        setPreferredSize(new Dimension(MccMod.MC_APPLET_W, MccMod.MC_APPLET_H));
    }

    public String setParameter(String name, String value) {
        synchronized (sharedState) {
            if (sharedState.isStarted) {
                throw new IllegalStateException("already started");
            }
        }
        return parameters.put(name, value);
    }

    public void startup() {
        synchronized (sharedState) {
            if (sharedState.isStarted) {
                throw new IllegalStateException("already started");
            }
            sharedState.isStarted = true;
        }
        // MasaoConstruction#start() will do nothing
        init();
        // MasaoConstruction#start() will start a thread
        // run() will be executed in a separated thread
        start();
    }

    public abstract void runHooked();

    // MasaoConstruction#start() will start a thread
    // Raname: MasaoConstruction#run() => runHooked()
    // MasaoConstruction will not implement run() and will implement runHooked()
    // instead
    @Override
    public void run() {
        System.out.println("AppletMod run start");
        synchronized (sharedState) {
            if (sharedState.isExiting) {
                System.out.println("AppletMod run end (without runHooked)");
                return;
            }
            sharedState.mcThread = Thread.currentThread();
        }
        runHooked();
        System.out.println("AppletMod run end (runHooked was interrupted)");
    }

    public void shutdown() {
        synchronized (sharedState) {
            if (!sharedState.isStarted) {
                throw new IllegalStateException("not started");
            }
            sharedState.isExiting = true;
            if (sharedState.mcThread != null) {
                sharedState.mcThread.interrupt();
            }
        }
        // MasaoConstruction#stop() will do { this.th = null; }
        // It is meaningless...
        stop();
        // MasaoConstruction#destroy() will do nothing
        destroy();
    }

    // ----- java.applet.Applet compatible (Do not call directly) -----

    public String getParameter(String name) {
        String value = parameters.get(name);
        System.out.printf("AppletMod getParameter: %s=%s%n", name, value);
        return value;
    }

    public URL getDocumentBase() {
        System.out.println("AppletMod getDocumentBase: null");
        return null;
    }

    public Image getImage(URL url, String name) {
        System.out.printf("AppletMod getImage: %s, %s%n", url, name);
        try {
            return ImageIO.read(getClass().getResource(name));
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    public void init() {
        System.out.println("AppletMod init");
    }

    public void start() {
        System.out.println("AppletMod start");
    }

    public void stop() {
        System.out.println("AppletMod stop");
    }

    public void destroy() {
        System.out.println("AppletMod destroy");
    }

    // public void paint(java.awt.Graphics g) {
    // System.out.println("paint");
    // }

    // public void update(java.awt.Graphics g) {
    // System.out.println("update");
    // }

}
