/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.yappy.mccport;

import java.awt.Image;
import java.awt.Panel;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;

import javax.imageio.ImageIO;

public class AppletMod extends Panel {

    private Map<String, String> parameters = new HashMap<>();

    public AppletMod() {
        System.out.println("AppletMod constructor");
    }

    public String setParameter(String name, String value) {
        return parameters.put(name, value);
    }

    // java.applet.Applet compatible -------------------------------------------

    public String getParameter(String name) {
        String value = parameters.get(name);
        System.out.println("AppletMod getParameter: " + name + " = " + value);
        return value;
    }

    public URL getDocumentBase() {
        System.out.println("AppletMod getDocumentBase: null");
        return null;
    }

    public Image getImage(URL url, String name) {
        System.out.println("AppletMod getImage: " + url + ", " + name);
        try {
            return ImageIO.read(getClass().getResource(name));
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    public void init() {
        System.out.println("AppletMod init");
    }

    public void start() {
        System.out.println("AppletMod start");
    }

    public void stop() {
        System.out.println("AppletMod stop");
    }

    public void destroy() {
        System.out.println("AppletMod destroy");
    }

    public void paint(java.awt.Graphics g) {
        System.out.println("paint");
    }

    public void update(java.awt.Graphics g) {
        System.out.println("update");
    }

}
