/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.yappy.mccport;

import java.io.IOException;
import java.util.List;

import com.google.common.collect.ImmutableList;

import javassist.ByteArrayClassPath;
import javassist.ClassClassPath;
import javassist.ClassMap;
import javassist.ClassPool;
import javassist.CtClass;
import javassist.NotFoundException;

public class MccMod {

    // Masao class names
    private static final List<String> MCC_CLASSES = ImmutableList.of("CharacterObject");
    // Replace class name map
    private static final ClassMap MCC_CLASS_MAP = new ClassMap();

    static {
        MCC_CLASS_MAP.put("java.applet.Applet", "io.github.yappy.mccport.AppletMod");
    }

    private static void addClass(String name) throws IOException, NotFoundException {
        byte[] b = MccMod.class.getClassLoader().getResourceAsStream(name + ".class").readAllBytes();
        ClassPool cp = ClassPool.getDefault();
        cp.insertClassPath(new ByteArrayClassPath(name, b));
    }

    public static void init() {
        ClassPool cp = ClassPool.getDefault();
        cp.insertClassPath(new ClassClassPath(MccMod.class));
        try {
            for (var clsName : MCC_CLASSES) {
                addClass(clsName);
                CtClass ctc = cp.get(clsName);
                ctc.replaceClassName(MCC_CLASS_MAP);
            }
            CtClass ctClsMc = cp.get("MasaoConstruction");

            Class<?> cls = ctClsMc.toClass();
            var con = cls.getDeclaredConstructor();
            var obj = con.newInstance();
            System.out.println(obj);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
