/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.yappy;

import org.junit.Test;
import io.github.yappy.MccMod;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        MccMod.init();
    }
}
