/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.yappy;

import io.github.yappy.mccport.MccMod;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        MccMod.init();
    }
}
