/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.yappy;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());

		Class cls = Class.forName("MasaoMakerSP");
		System.out.println(cls.newInstance());
    }
}
