# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Auto Build and Check

on: [push, pull_request]

permissions:
  contents: read

jobs:
  sh:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: shellcheck
      run: ./scripts/shellcheck.sh

  java:
    strategy:
      matrix:
        config:
          - os: 'ubuntu-latest'
            gradle: 'gradlew'
          - os: 'windows-latest'
            gradle: 'gradlew.bat'

    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell:  bash

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Install WiX
      if: runner.os == 'Windows'
      run: choco install wixtoolset

    - name: gradlew build
      run: ./${{ matrix.config.gradle }} -i build

    - name: gradlew jpackage
      run: ./${{ matrix.config.gradle }} -i jpackage

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: |
          **/build/reports/tests/test/
