# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        config:
          - os: 'ubuntu-latest'
            gradle: 'gradlew'
          - os: 'windows-latest'
            gradle: 'gradlew.bat'

    runs-on: ${{ matrix.config.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Install WiX
      if: runner.os == 'Windows'
      run: choco install wixtoolset

    - name: gradlew build
      run: ./${{ matrix.config.gradle }} -i build

    - name: gradlew jpackage
      run: ./${{ matrix.config.gradle }} -i jpackage
