# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Auto Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        config:
          - os: 'ubuntu-latest'
            gradle: 'gradlew'
            dist: true
          - os: 'windows-latest'
            gradle: 'gradlew.bat'
            dist: false

    runs-on: ${{ matrix.config.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Install WiX
      if: runner.os == 'Windows'
      run: choco install wixtoolset

    # including test + distZip
    - name: gradlew jpackage
      run: ./${{ matrix.config.gradle }} -i jpackage

    - name: Upload dist
      if: ${{ matrix.config.dist }}
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
      run: gh release upload ${{github.event.release.tag_name}} app/build/distributions/*.zip

    - name: Upload pkg
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
      run: gh release upload ${{github.event.release.tag_name}} app/build/pkg/*.*
